# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0593636b2a0abd0c655b1e8fd7111662"
name = "minimora"
application_url = "https://minimora.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://minimora.onrender.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://minimora.onrender.com/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://minimora.onrender.com/api/auth" ]
